/**
 * DOCX Writer Module
 * Converts rendered markdown content into professional .docx files
 */

import * as path from 'path';
import * as fs from 'fs';
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
  Footer,
  PageNumber,
} from 'docx';
import { logger } from '../utils/logger';
import { DocMetadata } from './markdown-writer';

// Resolve vibe-doc's own version at module load time so generated docs
// stamp the correct tool version. __dirname in dist/generator/ is one
// level below the package root.
const pkgVersion = (() => {
  try {
    const pkgPath = path.resolve(__dirname, '..', '..', 'package.json');
    return JSON.parse(fs.readFileSync(pkgPath, 'utf-8')).version as string;
  } catch {
    return 'unknown';
  }
})();

// Color scheme
const NAVY = '1B2A4A';
const STEEL = '3D5A80';
const MEDIUM_GRAY = '666666';

/**
 * Write rendered markdown content to a .docx file
 * @param renderedContent - The rendered markdown content
 * @param docType - Type of document (e.g., 'adr', 'runbook')
 * @param projectPath - Root path of the project
 * @param metadata - Document metadata
 * @returns Promise resolving to the full path of the written file
 */
export async function writeDocx(
  renderedContent: string,
  docType: string,
  projectPath: string,
  metadata: DocMetadata
): Promise<string> {
  // Create docs/generated directory
  const docsDir = path.join(projectPath, 'docs', 'generated');
  if (!fs.existsSync(docsDir)) {
    fs.mkdirSync(docsDir, { recursive: true });
    logger.debug('Created docs/generated directory', { path: docsDir });
  }

  // Parse markdown and convert to docx elements
  const sections = parseMarkdownContent(renderedContent, docType, metadata);

  // Create document
  const doc = new Document({
    sections: [
      {
        children: sections,
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [new TextRun({ children: [PageNumber.CURRENT] })],
              }),
            ],
          }),
        },
      },
    ],
  });

  // Write to file
  const buffer = await Packer.toBuffer(doc);
  const outputPath = path.join(docsDir, `${docType}.docx`);
  fs.writeFileSync(outputPath, buffer);

  logger.info('DOCX written', {
    docType,
    path: outputPath,
    size: buffer.length,
  });

  return outputPath;
}

/**
 * Parse markdown content and convert to docx Paragraph and Table objects
 */
function parseMarkdownContent(
  content: string,
  docType: string,
  metadata: DocMetadata
): (Paragraph | Table)[] {
  const sections: (Paragraph | Table)[] = [];
  const lines = content.split('\n');
  let isFirstH1 = true;

  // Add metadata header as paragraphs
  sections.push(
    new Paragraph({
      text: `Generated by Vibe Doc v${pkgVersion}`,
      spacing: { line: 240, lineRule: 'auto' },
    })
  );

  sections.push(
    new Paragraph({
      text: `Date: ${metadata.generatedAt}`,
    })
  );

  sections.push(
    new Paragraph({
      text: `Classification: ${metadata.classification}`,
    })
  );

  sections.push(
    new Paragraph({
      text: `Source artifacts: ${metadata.sourceArtifacts} files scanned`,
    })
  );

  sections.push(
    new Paragraph({
      text: `Confidence: ${metadata.confidenceSummary.high} high, ${metadata.confidenceSummary.medium} medium, ${metadata.confidenceSummary.low} low sections`,
      spacing: { after: 400 },
    })
  );

  // Parse markdown lines
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    const trimmed = line.trim();

    // Skip empty lines
    if (!trimmed) {
      i++;
      continue;
    }

    // Heading 1
    if (trimmed.startsWith('# ')) {
      const text = trimmed.slice(2).trim();
      const h1Paragraph = new Paragraph({
        children: [
          new TextRun({
            text,
            bold: true,
            size: 32, // 16pt (in twips)
            color: NAVY,
          }),
        ],
        spacing: { before: isFirstH1 ? 240 : 0, after: 120 },
        pageBreakBefore: !isFirstH1,
      });
      sections.push(h1Paragraph);
      isFirstH1 = false;
      i++;
      continue;
    }

    // Heading 2
    if (trimmed.startsWith('## ')) {
      const text = trimmed.slice(3).trim();
      sections.push(
        new Paragraph({
          children: [
            new TextRun({
              text,
              bold: true,
              size: 28, // 14pt (in twips)
              color: STEEL,
            }),
          ],
          spacing: { before: 200, after: 100 },
        })
      );
      i++;
      continue;
    }

    // Heading 3
    if (trimmed.startsWith('### ')) {
      const text = trimmed.slice(4).trim();
      sections.push(
        new Paragraph({
          children: [
            new TextRun({
              text,
              bold: true,
              size: 24, // 12pt (in twips)
              color: MEDIUM_GRAY,
            }),
          ],
          spacing: { before: 160, after: 80 },
        })
      );
      i++;
      continue;
    }

    // Bullet list
    if (trimmed.startsWith('- ')) {
      const bulletItems: string[] = [];
      while (i < lines.length && lines[i].trim().startsWith('- ')) {
        bulletItems.push(lines[i].trim().slice(2).trim());
        i++;
      }
      sections.push(
        ...bulletItems.map(
          (item) =>
            new Paragraph({
              text: item,
              bullet: {
                level: 0,
              },
              spacing: { line: 240 },
            })
        )
      );
      continue;
    }

    // Code block (triple backticks)
    if (trimmed.startsWith('```')) {
      i++; // Skip opening backticks
      const codeLines: string[] = [];
      while (i < lines.length && !lines[i].trim().startsWith('```')) {
        codeLines.push(lines[i]);
        i++;
      }
      i++; // Skip closing backticks

      sections.push(
        new Paragraph({
          text: codeLines.join('\n'),
          spacing: { before: 120, after: 120 },
          border: {
            top: { color: 'CCCCCC', space: 1, style: BorderStyle.SINGLE, size: 6 },
            bottom: { color: 'CCCCCC', space: 1, style: BorderStyle.SINGLE, size: 6 },
            left: { color: 'CCCCCC', space: 1, style: BorderStyle.SINGLE, size: 6 },
            right: { color: 'CCCCCC', space: 1, style: BorderStyle.SINGLE, size: 6 },
          },
        })
      );
      continue;
    }

    // Table (simple pipe-separated)
    if (trimmed.startsWith('|')) {
      const tableLines: string[] = [];
      while (i < lines.length && lines[i].trim().startsWith('|')) {
        tableLines.push(lines[i].trim());
        i++;
      }

      if (tableLines.length > 0) {
        const table = parseMarkdownTable(tableLines);
        sections.push(table);
      }
      continue;
    }

    // Regular paragraph
    if (trimmed) {
      sections.push(
        new Paragraph({
          text: trimmed,
          spacing: { line: 240, after: 80 },
        })
      );
      i++;
      continue;
    }

    i++;
  }

  return sections;
}

/**
 * Parse a markdown table and convert to docx Table
 */
function parseMarkdownTable(tableLines: string[]): Table {
  const rows: TableRow[] = [];

  for (const line of tableLines) {
    const cells = line
      .split('|')
      .map((cell) => cell.trim())
      .filter((cell) => cell.length > 0);

    rows.push(
      new TableRow({
        children: cells.map(
          (cellText) =>
            new TableCell({
              children: [
                new Paragraph({
                  text: cellText,
                }),
              ],
            })
        ),
      })
    );
  }

  return new Table({
    rows,
    width: { size: 100, type: WidthType.PERCENTAGE },
  });
}
